import { test, expect } from '@playwright/test';
import { encode } from '../../src/transfer.js';
import { emptyState } from '../../src/model.js';
const state = { version: 1, records: { measles: { plan: 'track', target: 2, nextDate: '', doses: [{ id: 'one', date: '2020-03-01', type: 'MMR' }] } } };
async function importState(page, incoming = state) {
  await page.goto('/#transfer=' + encode(incoming));
  await page.getByRole('button', { name: 'Replace with this record' }).click();
}
async function openDisease(page, id) { await page.locator(`details[data-id="${id}"] summary`).click(); return page.locator(`details[data-id="${id}"]`); }
test('log, edit, complete, remind, skip, persist, and delete a dose', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await importState(page);
  let row = await openDisease(page, 'measles');
  await row.getByRole('button', { name: 'Add dose' }).click();
  await page.getByLabel('Vaccination date').fill('2021-03-01');
  await page.getByLabel('Vaccine type / brand').fill('MMR test');
  await page.getByRole('button', { name: 'Save vaccination', exact: true }).click();
  await expect(page.locator('[data-id="measles"] .badge')).toHaveText('Series complete');
  await page.reload();
  row = await openDisease(page, 'measles');
  await expect(row).toContainText('MMR test');
  await row.getByRole('button', { name: 'Edit', exact: true }).last().click();
  await page.getByLabel('Vaccine type / brand').fill('Updated brand');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await row.getByRole('button', { name: 'Edit plan' }).click();
  await page.getByLabel('Next review / dose date').fill('2022-01-01');
  await page.getByRole('button', { name: 'Save plan' }).click();
  await expect(row.locator('.badge')).toHaveText('Reminder due');
  await row.getByRole('button', { name: 'Edit plan' }).click();
  await page.getByLabel('Plan status').selectOption('skip');
  await page.getByRole('button', { name: 'Save plan' }).click();
  await expect(row.locator('.badge')).toHaveText('Not in your plan');
  await row.getByRole('button', { name: 'Edit', exact: true }).last().click();
  await page.getByRole('button', { name: 'Delete dose', exact: true }).click();
  await page.getByRole('button', { name: 'Delete dose', exact: true }).click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('everwell.records.v1')));
  expect(saved.records.measles.doses).toHaveLength(1);
  expect(errors).toEqual([]);
});
test('combination vaccine, search, exact export and QR image import', async ({ page, browser }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Log vaccination', exact: true }).click();
  await page.getByRole('combobox').selectOption('combo:mmr');
  await page.getByLabel('Vaccination date').fill('2020-04-01');
  await page.getByRole('button', { name: 'Save vaccination', exact: true }).click();
  await page.getByRole('searchbox').fill('German');
  await expect(page.locator('details.disease')).toHaveCount(1);
  await expect(page.locator('details.disease')).toContainText('Rubella');
  await page.getByRole('button', { name: 'Transfer records', exact: true }).click();
  await expect(page.locator('#qr-canvas')).toBeVisible();
  const code = await page.locator('#export-code').inputValue();
  const original = await page.evaluate(() => JSON.parse(localStorage.getItem('everwell.records.v1')));
  const qr = await page.locator('#qr-canvas').screenshot();
  const context = await browser.newContext(); const other = await context.newPage();
  await other.goto('/');
  await other.getByRole('button', { name: 'Transfer records', exact: true }).click();
  await other.getByRole('button', { name: 'Import a record' }).click();
  await other.getByLabel('Upload QR image').setInputFiles({ name: 'qr.png', mimeType: 'image/png', buffer: qr });
  await expect(other.getByText('Ready to import', { exact: true })).toBeVisible();
  await other.getByRole('button', { name: 'Replace with this record' }).click();
  const restored = await other.evaluate(() => JSON.parse(localStorage.getItem('everwell.records.v1')));
  expect(restored).toEqual(original); expect(Object.keys(restored.records)).toHaveLength(3);
  expect(code).toMatch(/^EV1\./);
  await context.close();
});
test('malformed import leaves saved data unchanged, empty replacement works, mobile fits', async ({ page }) => {
  await importState(page);
  await page.getByRole('button', { name: 'Transfer records', exact: true }).click();
  await page.getByRole('button', { name: 'Import a record' }).click();
  await page.getByLabel('Transfer code or link').fill('invalid');
  await page.getByRole('button', { name: 'Preview import' }).click();
  await expect(page.locator('#modal-error')).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('everwell.records.v1')))).toEqual(state);
  await page.getByLabel('Transfer code or link').fill(encode(emptyState()));
  await page.getByRole('button', { name: 'Preview import' }).click();
  await page.getByRole('button', { name: 'Replace with this record' }).click();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('everwell.records.v1')))).toEqual(emptyState());
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('starter plan and keyboard-accessible record editing', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Explore the Finnish starter plan' }).click();
  await page.getByRole('button', { name: 'Use starter plan' }).click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('everwell.records.v1')));
  expect(Object.keys(saved.records)).toHaveLength(7);
  expect(saved.records.rubella.target).toBe(2);
  const summary = page.locator('details[data-id="polio"] summary');
  await summary.focus(); await page.keyboard.press('Enter');
  await expect(page.locator('details[data-id="polio"] .disease-body')).toBeVisible();
});
